#!/usr/bin/env python3

# Standalone DigitalOwnership verifier. Generated by scripts/syncDownloadArtifacts.js.

import hashlib
import json
import os
import shlex
import zipfile
from pathlib import Path
from urllib.parse import urlparse


HASH_ALGORITHM = "SHA-512"
HASH_SCOPE = "digitalownership-content-v1"
METADATA_PREFIX = "DigitalOwnership."
PENDING_REGISTRATION_MARKERS = {"web-registration-pending"}
CONFIG_FILE = Path(__file__).resolve().with_name("digitalownership_config.json")
ODF_VOLATILE_ENTRIES = {"meta.xml", "settings.xml", "styles.xml"}
ODF_VOLATILE_PREFIXES = ("Thumbnails/",)
OOXML_FORMATS = {
    "docx": {
        "required": "word/document.xml",
        "prefixes": ("word/",),
        "volatile": {"word/settings.xml"},
    },
    "xlsx": {
        "required": "xl/workbook.xml",
        "prefixes": ("xl/",),
        "volatile": {"xl/calcChain.xml"},
    },
    "pptx": {
        "required": "ppt/presentation.xml",
        "prefixes": ("ppt/",),
        "volatile": set(),
    },
}


def compute_document_hash(path):
    doc_path = Path(path)
    if not zipfile.is_zipfile(doc_path):
        raise UnsupportedDocumentFormat(
            f"Unsupported file format for stable DigitalOwnership hashing: {doc_path.suffix or doc_path.name}"
        )
    with zipfile.ZipFile(doc_path, "r") as package:
        names = set(package.namelist())
        if _is_odf_package(names):
            return _compute_package_hash(package, _odf_hash_entries(package))
        ooxml_format = _ooxml_format(names)
        if ooxml_format:
            return _compute_package_hash(package, _ooxml_hash_entries(package, ooxml_format))
    raise UnsupportedDocumentFormat(
        f"Unsupported ZIP-based document format for stable DigitalOwnership hashing: {doc_path.suffix or doc_path.name}"
    )


class UnsupportedDocumentFormat(RuntimeError):
    pass


def bundled_config():
    try:
        with CONFIG_FILE.open("r", encoding="utf-8") as handle:
            data = json.load(handle)
    except FileNotFoundError:
        return {}
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Invalid DigitalOwnership config file: {CONFIG_FILE}") from exc
    if not isinstance(data, dict):
        raise RuntimeError(f"DigitalOwnership config must be a JSON object: {CONFIG_FILE}")
    return data


_BUNDLED_CONFIG = bundled_config()


def config_value(env_name, config_name, default=""):
    value = os.environ.get(env_name)
    if value is not None:
        return value
    configured = _BUNDLED_CONFIG.get(config_name)
    if configured is None:
        return default
    return str(configured)


def _is_odf_package(names):
    return "mimetype" in names and any(name in names for name in ("content.xml", "META-INF/manifest.xml"))


def _ooxml_format(names):
    if "[Content_Types].xml" not in names:
        return None
    for format_name, config in OOXML_FORMATS.items():
        if config["required"] in names:
            return format_name
    return None


def _odf_hash_entries(package):
    return sorted(
        info.filename
        for info in package.infolist()
        if not info.is_dir()
        and info.filename not in ODF_VOLATILE_ENTRIES
        and not info.filename.startswith(ODF_VOLATILE_PREFIXES)
    )


def _ooxml_hash_entries(package, format_name):
    config = OOXML_FORMATS[format_name]
    return sorted(
        info.filename
        for info in package.infolist()
        if not info.is_dir()
        and info.filename.startswith(config["prefixes"])
        and info.filename not in config["volatile"]
    )


def _compute_package_hash(package, names):
    digest = hashlib.sha512()
    for name in names:
        data = package.read(name)
        file_digest = hashlib.sha512(data).hexdigest()
        digest.update(b"FILE\x00")
        digest.update(name.encode("utf-8"))
        digest.update(b"\x00")
        digest.update(str(len(data)).encode("ascii"))
        digest.update(b"\x00")
        digest.update(file_digest.encode("ascii"))
        digest.update(b"\x00")
    return digest.hexdigest()


def run_json_command(command, doc_hash, doc_path, *extra_args):
    if not command:
        raise RuntimeError("No command configured")

    args = shlex.split(command)
    completed = subprocess.run(
        args + [doc_hash, str(doc_path), *extra_args],
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        message = completed.stderr.strip() or completed.stdout.strip()
        raise RuntimeError(message or f"command failed with exit code {completed.returncode}")

    try:
        return json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"command did not return JSON: {completed.stdout[:500]}") from exc


def registrar_command():
    if os.environ.get("DO_MOCK_CHAIN") == "1":
        return os.environ.get("DO_REGISTRAR_CMD")
    return os.environ.get("DO_REGISTRAR_CMD")


def verifier_command():
    if os.environ.get("DO_MOCK_CHAIN") == "1":
        return os.environ.get("DO_VERIFIER_CMD")
    return os.environ.get("DO_VERIFIER_CMD")


def web_registration_url():
    return config_value("DO_WEB_REGISTRATION_URL", "webRegistrationUrl")


def web_account_url():
    configured = config_value("DO_WEB_ACCOUNT_URL", "webAccountUrl")
    if configured:
        return configured

    registration_url = web_registration_url()
    if not registration_url:
        return ""
    if registration_url.rstrip("/").endswith("/app"):
        return registration_url.rstrip("/")[:-4] + "/account"
    return registration_url


def web_plugin_api_url():
    configured = config_value("DO_WEB_PLUGIN_API_URL", "webPluginApiUrl")
    if configured:
        return configured.rstrip("/")

    account_url = web_account_url()
    if not account_url:
        return ""

    parsed = urlparse(account_url)
    if not parsed.scheme or not parsed.netloc:
        return ""
    return f"{parsed.scheme}://{parsed.netloc}/api/plugin"


def web_verification_url():
    configured = config_value("DO_WEB_VERIFICATION_URL", "webVerificationUrl")
    if configured:
        return configured

    registration_url = web_registration_url()
    if not registration_url:
        return ""

    parsed = urlparse(registration_url)
    if not parsed.scheme or not parsed.netloc:
        return ""
    return f"{parsed.scheme}://{parsed.netloc}/api/verify/hash"


def _account_registration_api_urls(plugin_api_url):
    normalized = str(plugin_api_url or "").strip().rstrip("/")
    if not normalized:
        return []

    seen = set()
    candidates = []

    def add(candidate):
        if candidate and candidate not in seen:
            seen.add(candidate)
            candidates.append(candidate)

    bases = [normalized]
    if normalized.endswith("/register/email-anchored"):
        bases.append(normalized[: -len("/register/email-anchored")])
    elif normalized.endswith("/register"):
        bases.append(normalized[: -len("/register")])
    if normalized.endswith("/api/plugin"):
        bases.append(normalized[: -len("/api/plugin")] + "/api")

    for base in bases:
        if base.endswith("/api/plugin"):
            add(f"{base}/register/email-anchored")
            add(f"{base[:-len('/api/plugin')]}/api/register/email-anchored")
            continue
        add(f"{base}/register/email-anchored")

    return candidates


def chain_name():
    return config_value("DO_CHAIN_NAME", "chainName", "unknown")


def contract_address():
    return config_value("DO_CONTRACT_ADDRESS", "contractAddress")


def do_email_registration_addresses():
    value = os.environ.get("DO_EMAIL_REGISTRATION_ADDRESSES")
    if value is None:
        configured = _BUNDLED_CONFIG.get("doEmailRegistrationAddresses")
        if isinstance(configured, list):
            value = ",".join(str(item) for item in configured)
        elif configured is not None:
            value = str(configured)
        else:
            value = ""

    addresses = []
    for item in str(value).split(","):
        normalized = str(item).strip().lower()
        if normalized:
            addresses.append(normalized)
    return addresses


def preferred_browser_bundle_ids():
    value = os.environ.get("DO_PREFERRED_BROWSER_BUNDLE_IDS")
    if value is not None:
        return [item.strip() for item in value.split(",") if item.strip()]
    configured = _BUNDLED_CONFIG.get("preferredBrowserBundleIds")
    if isinstance(configured, list):
        return [str(item).strip() for item in configured if str(item).strip()]
    return []


def metadata_name(name):
    return f"{METADATA_PREFIX}{name}"


def registration_is_pending(value):
    return str(value or "").strip().lower() in PENDING_REGISTRATION_MARKERS


def registration_is_complete(value):
    normalized = str(value or "").strip().lower()
    return bool(normalized) and normalized not in PENDING_REGISTRATION_MARKERS

import argparse
import json
import os
import shlex
import subprocess
import sys
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen


EMAIL_REGISTRATION_SCOPE = "digitalownership-email-v1"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Verify a document with the DigitalOwnership content hash algorithm.",
    )
    parser.add_argument("document", help="Path to the document to verify.")
    parser.add_argument(
        "--expected-hash",
        help="Expected DigitalOwnership.Hash value. If provided, the command compares it with the computed hash.",
    )
    parser.add_argument(
        "--scope",
        default=HASH_SCOPE,
        help=f"Expected hash scope. Default: {HASH_SCOPE}.",
    )
    parser.add_argument(
        "--chain",
        action="store_true",
        help="Also check whether the computed hash is registered on-chain.",
    )
    parser.add_argument(
        "--email",
        default="",
        help="Email address used for account registration without MetaMask. The value is normalized to lowercase.",
    )
    parser.add_argument(
        "--verifier-cmd",
        default=os.environ.get("DO_VERIFIER_CMD", ""),
        help="Verifier command used with --chain. Defaults to DO_VERIFIER_CMD. For the website verifier, prefer DO_WEB_VERIFICATION_URL='https://digitalownership.squaredant.com/api/verify/hash'.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON.",
    )
    return parser.parse_args()


def registry_key_from_hash(document_hash):
    try:
        from Crypto.Hash import keccak
    except ImportError:
        return None
    digest = keccak.new(digest_bits=256)
    digest.update(document_hash.encode("utf-8"))
    return f"0x{digest.hexdigest()}"


def normalize_email_anchor(value):
    return str(value or "").strip().lower()


def email_anchored_registry_key_from_hash(document_hash, email):
    normalized_hash = str(document_hash or "").strip().lower()
    normalized_email = normalize_email_anchor(email)
    if not normalized_email:
        return None
    try:
        from Crypto.Hash import keccak
    except ImportError:
        return None
    if len(normalized_hash) != 128 or any(ch not in "0123456789abcdef" for ch in normalized_hash):
        return None

    email_digest = keccak.new(digest_bits=256)
    email_digest.update(f"{EMAIL_REGISTRATION_SCOPE}:email:{normalized_email}".encode("utf-8"))
    email_claim_hash = f"0x{email_digest.hexdigest()}"

    registry_digest = keccak.new(digest_bits=256)
    registry_digest.update(
        f"{EMAIL_REGISTRATION_SCOPE}:registration:{normalized_hash}:{email_claim_hash}".encode("utf-8")
    )
    return f"0x{registry_digest.hexdigest()}"


def read_package_metadata(path):
    result = {}
    try:
        with zipfile.ZipFile(path, "r") as package:
            names = set(package.namelist())
            if "meta.xml" in names:
                result.update(read_odf_metadata(package.read("meta.xml")))
            if "docProps/custom.xml" in names:
                result.update(read_ooxml_metadata(package.read("docProps/custom.xml")))
    except Exception:
        return {}
    return result


def read_odf_metadata(data):
    result = {}
    root = ET.fromstring(data)
    for element in root.iter():
        name = None
        for attr_name, attr_value in element.attrib.items():
            if attr_name.endswith("}name") or attr_name == "name":
                name = attr_value
                break
        if not name or not name.startswith(METADATA_PREFIX):
            continue
        result[name.removeprefix(METADATA_PREFIX)] = "".join(element.itertext())
    return result


def read_ooxml_metadata(data):
    result = {}
    root = ET.fromstring(data)
    for prop in root:
        name = prop.attrib.get("name")
        if not name or not name.startswith(METADATA_PREFIX):
            continue
        value = "".join(prop.itertext())
        result[name.removeprefix(METADATA_PREFIX)] = value
    return result


def verify_online(document_hash, document_path, verifier_cmd, email=""):
    if verifier_cmd:
        if not email:
            return run_json_command(verifier_cmd, document_hash, Path(document_path))
        args = shlex.split(verifier_cmd)
        completed = subprocess.run(
            args + [document_hash, str(Path(document_path)), "--email", normalize_email_anchor(email)],
            check=False,
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            message = completed.stderr.strip() or completed.stdout.strip()
            raise RuntimeError(message or f"verifier command failed with exit code {completed.returncode}")
        try:
            return json.loads(completed.stdout)
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"verifier command did not return JSON: {completed.stdout[:500]}") from exc

    verify_url = web_verification_url()
    if not verify_url:
        raise RuntimeError("--chain requires --verifier-cmd, DO_VERIFIER_CMD, or a configured web verification URL.")

    separator = "&" if "?" in verify_url else "?"
    params = {"hash": document_hash}
    normalized_email = normalize_email_anchor(email)
    if normalized_email:
        params["email"] = normalized_email
    url = f"{verify_url}{separator}{urlencode(params)}"
    request = Request(url, headers={"Accept": "application/json"})
    with urlopen(request, timeout=30) as response:
        payload = response.read().decode("utf-8")
    return json.loads(payload)


def main():
    args = parse_args()
    result = {
        "ok": False,
        "document": str(Path(args.document).expanduser()),
        "hashAlgorithm": HASH_ALGORITHM,
        "hashScope": HASH_SCOPE,
        "expectedScope": args.scope,
        "hash": "",
        "registryKey": None,
        "hashMatches": None,
        "metadata": {},
        "metadataHashMatches": None,
        "chain": None,
    }

    try:
        if args.scope != HASH_SCOPE:
            raise RuntimeError(f"Unsupported hash scope {args.scope!r}; this verifier implements {HASH_SCOPE!r}.")

        document_hash = compute_document_hash(args.document)
        result["hash"] = document_hash
        result["registryKey"] = (
            email_anchored_registry_key_from_hash(document_hash, args.email)
            if args.email
            else registry_key_from_hash(document_hash)
        )
        if args.email:
            result["registrationMethod"] = "email_anchored_account"
            result["emailAnchor"] = normalize_email_anchor(args.email)
        else:
            result["registrationMethod"] = "wallet_or_document_key"
        result["metadata"] = read_package_metadata(args.document)
        metadata_hash = result["metadata"].get("Hash")
        if metadata_hash:
            result["metadataHashMatches"] = document_hash.lower() == metadata_hash.strip().lower()

        if args.expected_hash:
            result["hashMatches"] = document_hash.lower() == args.expected_hash.strip().lower()
            if not result["hashMatches"]:
                raise RuntimeError("Computed hash does not match the expected hash.")

        if args.chain:
            chain_result = verify_online(document_hash, args.document, args.verifier_cmd, args.email)
            result["chain"] = chain_result
            if not chain_result.get("ok"):
                raise RuntimeError("On-chain verification failed.")

        result["ok"] = True
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            print(f"Document: {result['document']}")
            print(f"Hash algorithm: {HASH_ALGORITHM}")
            print(f"Hash scope: {HASH_SCOPE}")
            print(f"Hash: {document_hash}")
            if result["registryKey"]:
                print(f"Registry key: {result['registryKey']}")
            if args.email:
                print(f"Account email: {normalize_email_anchor(args.email)}")
            if result["hashMatches"] is not None:
                print(f"Expected hash match: {result['hashMatches']}")
            if result["metadata"]:
                print(f"DigitalOwnership metadata: {', '.join(sorted(result['metadata']))}")
                if result["metadataHashMatches"] is False:
                    print("Metadata note: older DigitalOwnership metadata refers to a different fingerprint.")
            if result["chain"] is not None:
                print(f"On-chain verification: {result['chain'].get('ok')}")
                if result["chain"].get("registryKey"):
                    print(f"Registry key: {result['chain']['registryKey']}")
                if result["chain"].get("txHash"):
                    print(f"Transaction: {result['chain']['txHash']}")
        return 0
    except (RuntimeError, UnsupportedDocumentFormat) as exc:
        result["error"] = str(exc)
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            print(f"Verification failed: {exc}", file=sys.stderr)
            if result["hash"]:
                print(f"Computed hash: {result['hash']}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
